name: Release Go Binary

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"

      - name: Build binary
        run: |
          go build -v -o semver-calculator
          tar -czvf semver-calculator-linux-amd64.tar.gz semver-calculator

      - name: Calculate checksum
        run: sha256sum semver-calculator-linux-amd64.tar.gz > semver-calculator-linux-amd64.tar.gz.sha256

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            semver-calculator-linux-amd64.tar.gz
            semver-calculator-linux-amd64.tar.gz.sha256
          generate_release_notes: true
